"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { ProofUpload } from "@/components/proof-upload";
import { ProofGuidance, type ProofGuidanceData } from "@/components/proof-guidance";
import { toast } from "sonner";
import { ContractStatus } from "@/types";
import { XRPL_EVM_CHAIN_ID, ERC20_ABI, toRLUSDUnits } from "@/lib/evm-abi";
import { ethers } from "ethers";

interface ContractActionsProps {
  contractId: string;
  status: ContractStatus;
  investorAddress: string;
  startupAddress: string | null;
  amountRLUSD: string;
  cancelAfter: string;
  milestoneId: string | null;
  milestoneTitle: string | null;
  milestoneNumber: number | null;
  totalMilestones: number;
  latestProofId: string | null;
  latestProofReasoning: string | null;
  latestProofConfidence: number | null;
  latestProofFileUrl: string | null;
  latestProofFileName: string | null;
  viewerWallet: string | null;
  /** Pre-fetched AI proof guidance for the active milestone (null = not yet generated). */
  milestoneGuidance: ProofGuidanceData | null;
  /** Structured rejection reasons generated by AI at rejection time. */
  latestProofAiObjections: Array<{ code: string; description: string }> | null;
  /** Appeal status for the latest proof: null = no appeal, "APPROVED" = overturned, "REJECTED" = upheld. */
  latestProofAppealStatus: string | null;
  /** "OVERTURNED" | "UPHELD" — the appeal verdict. */
  latestProofAppealResult: string | null;
  /** Claude's reasoning for the appeal verdict. */
  latestProofAppealReasoning: string | null;
  // ── Feature G: Progress Check-ins ────────────────────────────────────────
  /** Progress updates logged by the startup for the active milestone. */
  progressUpdates: Array<{ id: string; text: string; source: string; createdAt: string }>;
  // ── Feature F: Renegotiation ──────────────────────────────────────────────
  /** Current renegotiation sub-status: null | "RENEGOTIATING" | "EXTENSION_REQUESTED" | "EXTENSION_APPROVED" | "EXTENSION_REJECTED" */
  renegotiationStatus: string | null;
  /** ISO string — when the 48-hour window closes */
  renegotiationDeadline: string | null;
  /** Progress update text submitted by startup */
  interimUpdateText: string | null;
  /** AI plausibility assessment (2-sentence summary) */
  interimAiAssessment: string | null;
  /** true = AI thinks completion is plausible */
  interimAiPositive: boolean | null;
  /** Extension days requested: 7 | 14 | 30 */
  extensionDays: number | null;
  /** True when this is a demo contract — bypasses MetaMask, role checks, and real blockchain calls. */
  isDemo?: boolean;
  // ── Enterprise Attestation Mode ───────────────────────────────────────────
  /** "ESCROW" | "ATTESTATION" */
  contractMode: string;
  dataSourceType: string | null;
  dataSourceUrl: string | null;
  dataSourceApiKeyHint: string | null;
  dataSourceLockedAt: string | null;
  scheduleType: string | null;
  scheduleNextRun: string | null;
  attestationFetchedAt: string | null;
  attestationFetchedHash: string | null;
  attestationCertUrl: string | null;
}

// ─── MetaMask helpers ────────────────────────────────────────────────────────

declare global {
  interface Window {
    ethereum?: {
      request: (args: { method: string; params?: unknown[] }) => Promise<unknown>;
      isMetaMask?: boolean;
    };
  }
}

/** Extract a human-readable message from any thrown value (Error or MetaMask object). */
function extractError(err: unknown): string {
  if (!err) return "Unknown error";
  if (err && typeof err === "object") {
    const e = err as Record<string, unknown>;
    // MetaMask wraps the real reason in error.data.message or error.data
    if (e.data && typeof e.data === "object") {
      const d = e.data as Record<string, unknown>;
      if (typeof d.message === "string") return d.message;
    }
    // Solidity revert strings come through error.reason
    if (typeof e.reason === "string") return e.reason;
    // ethers v6 nests them here
    if (e.error && typeof e.error === "object") {
      const inner = e.error as Record<string, unknown>;
      if (typeof inner.message === "string") return inner.message;
    }
    if (typeof e.message === "string") {
      const msg = e.message as string;
      // ThirdWeb-managed RPC error — replace with user-friendly message
      if (msg.includes("thirdweb support") || msg.includes("We are not able to process your request")) {
        return "The XRPL EVM network is temporarily unavailable. Please wait a moment and try again.";
      }
      // Strip the generic "Internal JSON-RPC error" wrapper if there's nested info
      if (msg.includes("Internal JSON-RPC error") || msg.includes("execution reverted")) {
        try {
          // Sometimes the revert reason is JSON-encoded inside the message
          const jsonStart = msg.indexOf("{");
          if (jsonStart !== -1) {
            const parsed = JSON.parse(msg.slice(jsonStart)) as Record<string, unknown>;
            if (typeof parsed.message === "string") return parsed.message;
          }
        } catch {}
      }
      return msg;
    }
  }
  if (err instanceof Error) {
    const msg = err.message;
    if (msg.includes("thirdweb support") || msg.includes("We are not able to process your request")) {
      return "The XRPL EVM network is temporarily unavailable. Please wait a moment and try again.";
    }
    return msg;
  }
  return String(err);
}

/** Ensure MetaMask is connected and on the XRPL EVM chain (always refreshes RPC). */
async function connectMetaMask(): Promise<string> {
  if (!window.ethereum) {
    throw new Error(
      "MetaMask is not installed. Please install MetaMask to fund the escrow."
    );
  }
  const accounts = (await window.ethereum.request({
    method: "eth_requestAccounts",
  })) as string[];

  if (!accounts || accounts.length === 0) {
    throw new Error("No MetaMask account selected.");
  }

  const targetChainId = `0x${XRPL_EVM_CHAIN_ID.toString(16)}`;
  const chainParams = {
    chainId: targetChainId,
    chainName: "XRPL EVM Sidechain Testnet",
    nativeCurrency: { name: "XRP", symbol: "XRP", decimals: 18 },
    rpcUrls: [process.env.NEXT_PUBLIC_EVM_RPC_URL ?? "https://rpc.testnet.xrplevm.org"],
    blockExplorerUrls: ["https://explorer.xrplevm.org"],
  };

  // Always call addEthereumChain to keep RPC up to date.
  // If chain already exists MetaMask shows a one-time "update" prompt.
  try {
    await window.ethereum.request({ method: "wallet_addEthereumChain", params: [chainParams] });
  } catch {
    // User dismissed the update prompt or chain switch failed — try a plain switch
    try {
      await window.ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: targetChainId }] });
    } catch (switchErr) {
      throw new Error(`Failed to switch to XRPL EVM chain: ${extractError(switchErr)}`);
    }
  }

  const chainAfter = (await window.ethereum.request({ method: "eth_chainId" })) as string;
  if (parseInt(chainAfter, 16) !== XRPL_EVM_CHAIN_ID) {
    throw new Error("Wrong network in MetaMask. Please switch to XRPL EVM Sidechain Testnet.");
  }

  return accounts[0].toLowerCase();
}

/** Send a raw EVM transaction and return the tx hash. */
async function sendTx(from: string, to: string, data: string): Promise<string> {
  const txHash = (await window.ethereum!.request({
    method: "eth_sendTransaction",
    params: [{ from, to, data }],
  })) as string;
  return txHash;
}

/** Call MockRLUSD.faucet(amount) to mint test tokens into the caller's wallet. */
async function callFaucet(from: string, amountUSD: string): Promise<void> {
  const rlusdAddress = process.env.NEXT_PUBLIC_RLUSD_CONTRACT_ADDRESS!;
  const iface = new ethers.Interface(ERC20_ABI);
  const amount = toRLUSDUnits(amountUSD);
  const data = iface.encodeFunctionData("faucet", [amount]);
  const txHash = await sendTx(from, rlusdAddress, data);
  await waitForReceipt(txHash);
}

/** Poll eth_getTransactionReceipt until the tx is mined (max 5 min). */
async function waitForReceipt(txHash: string): Promise<void> {
  const deadline = Date.now() + 5 * 60 * 1000;
  while (Date.now() < deadline) {
    const receipt = (await window.ethereum!.request({
      method: "eth_getTransactionReceipt",
      params: [txHash],
    })) as { status: string | number } | null;

    if (receipt) {
      // Normalize: some RPCs return 1 (number), "0x1", or "0x01" for success
      const statusOk = parseInt(String(receipt.status), 16) === 1;
      if (!statusOk) {
        throw new Error("Transaction reverted on-chain.");
      }
      return;
    }
    await new Promise((r) => setTimeout(r, 4000));
  }
  throw new Error("Transaction not mined within 5 minutes.");
}

/** Decode an ABI-encoded revert reason (0x08c379a0 selector + string). */
function decodeRevertReason(hexData: string): string | null {
  try {
    if (!hexData || !hexData.startsWith("0x08c379a0")) return null;
    const decoded = ethers.AbiCoder.defaultAbiCoder().decode(
      ["string"],
      "0x" + hexData.slice(10)
    );
    return decoded[0] as string;
  } catch {
    return null;
  }
}

/** Simulate a call via eth_call to get the revert reason before sending. */
async function simulateCall(from: string, to: string, data: string): Promise<void> {
  try {
    await window.ethereum!.request({
      method: "eth_call",
      params: [{ from, to, data }, "latest"],
    });
  } catch (err: unknown) {
    // Try to decode ABI-encoded revert reason from error.data first
    let revertReason = "";
    if (err && typeof err === "object") {
      const e = err as Record<string, unknown>;
      // MetaMask wraps it as error.data.data or error.data
      const rawData =
        typeof e.data === "string" ? e.data
        : e.data && typeof e.data === "object"
          ? (e.data as Record<string, unknown>).data as string | undefined
          : undefined;
      if (rawData) revertReason = decodeRevertReason(rawData) ?? "";
      if (!revertReason && typeof e.message === "string") revertReason = e.message;
    }
    if (!revertReason) revertReason = String(err);
    throw new Error(revertReason);
  }
}

// ─── Component ───────────────────────────────────────────────────────────────

export function ContractActions({
  contractId,
  status,
  investorAddress,
  startupAddress,
  amountRLUSD,
  cancelAfter,
  milestoneId,
  milestoneTitle,
  milestoneNumber,
  totalMilestones,
  latestProofId,
  latestProofReasoning,
  latestProofConfidence,
  latestProofFileUrl,
  latestProofFileName,
  viewerWallet,
  milestoneGuidance,
  latestProofAiObjections,
  latestProofAppealStatus,
  latestProofAppealResult,
  latestProofAppealReasoning,
  progressUpdates,
  renegotiationStatus,
  renegotiationDeadline,
  interimUpdateText,
  interimAiAssessment,
  interimAiPositive,
  extensionDays,
  isDemo,
  contractMode,
  dataSourceType,
  dataSourceUrl,
  dataSourceApiKeyHint,
  dataSourceLockedAt,
  scheduleType,
  scheduleNextRun,
  attestationFetchedAt,
  attestationFetchedHash,
  attestationCertUrl,
}: ContractActionsProps) {
  const [isMobileNoWallet, setIsMobileNoWallet] = useState(false);
  const [fundingStep, setFundingStep] = useState<
    "idle" | "approving" | "funding" | "confirming" | "done"
  >("idle");
  const [faucetLoading, setFaucetLoading] = useState(false);
  const [loadingVerify, setLoadingVerify] = useState(false);
  const [loadingReview, setLoadingReview] = useState<"APPROVE" | "REJECT" | null>(null);
  const [loadingFinish, setLoadingFinish] = useState(false);
  const [loadingCancel, setLoadingCancel] = useState(false);
  const [loadingResubmit, setLoadingResubmit] = useState(false);
  const [verifyDone, setVerifyDone] = useState(false);
  const [confirmCancel, setConfirmCancel] = useState(false);
  const [confirmReject, setConfirmReject] = useState(false);
  const [appealText, setAppealText] = useState("");
  const [loadingAppeal, setLoadingAppeal] = useState(false);
  const [renegotiationText, setRenegotiationText] = useState("");
  const [renegotiationExtDays, setRenegotiationExtDays] = useState<7 | 14 | 30>(14);
  const [loadingRenegotiate, setLoadingRenegotiate] = useState(false);
  const [loadingRenegotiateRespond, setLoadingRenegotiateRespond] = useState<"APPROVE" | "REJECT" | null>(null);
  const [confirmCancelReneg, setConfirmCancelReneg] = useState(false);
  const [progressUpdateText, setProgressUpdateText] = useState("");
  const [loadingProgressUpdate, setLoadingProgressUpdate] = useState(false);
  // ── Demo mode ─────────────────────────────────────────────────────────────
  const [demoStep, setDemoStep] = useState<"idle" | "loading" | "overlay">("idle");
  const [demoOverlayText, setDemoOverlayText] = useState<string | null>(null);

  async function advanceDemo(step: "fund" | "submit_proof" | "verify" | "release", overlayText: string) {
    setDemoOverlayText(overlayText);
    setDemoStep("overlay");
    await new Promise((r) => setTimeout(r, 2200));
    setDemoStep("loading");
    try {
      const res = await fetch("/api/demo/advance", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, step }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        toast.error(err.error ?? "Demo step failed");
        setDemoStep("idle");
        return;
      }
      if (step === "verify") {
        const data = (await res.json()) as { decision: string; confidence: number; reasoning: string };
        toast.success(`AI verified: ${data.decision} (${data.confidence}% confidence)`);
      }
      setTimeout(() => window.location.reload(), 800);
    } catch {
      toast.error("Something went wrong. Please try again.");
      setDemoStep("idle");
    }
  }

  // ── Feature I: Proof Pre-Check ────────────────────────────────────────────
  const [loadingPreCheck, setLoadingPreCheck] = useState(false);
  const [preCheckResult, setPreCheckResult] = useState<{
    verdict: "LIKELY_PASS" | "LIKELY_FAIL" | "BORDERLINE";
    feedback: string;
    suggestions: string[];
  } | null>(null);

  useEffect(() => {
    const isMobile = /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent);
    const hasWallet = typeof window !== "undefined" && !!window.ethereum;
    setIsMobileNoWallet(isMobile && !hasWallet);
  }, []);

  // Auto-reset confirm states after 5 seconds to prevent accidental clicks
  useEffect(() => {
    if (!confirmCancel) return;
    const t = setTimeout(() => setConfirmCancel(false), 5000);
    return () => clearTimeout(t);
  }, [confirmCancel]);

  useEffect(() => {
    if (!confirmReject) return;
    const t = setTimeout(() => setConfirmReject(false), 5000);
    return () => clearTimeout(t);
  }, [confirmReject]);

  useEffect(() => {
    if (!confirmCancelReneg) return;
    const t = setTimeout(() => setConfirmCancelReneg(false), 5000);
    return () => clearTimeout(t);
  }, [confirmCancelReneg]);

  // ── Attestation state ─────────────────────────────────────────────────────
  const [lockingSource, setLockingSource] = useState(false);
  const [sourceType, setSourceType] = useState<string>(dataSourceType ?? "URL_SCRAPE");
  const [sourceUrl, setSourceUrl] = useState(dataSourceUrl ?? "");
  const [sourceApiKey, setSourceApiKey] = useState("");
  const [testingSource, setTestingSource] = useState(false);
  const [testPreview, setTestPreview] = useState<string | null>(null);
  const [runningAttestation, setRunningAttestation] = useState(false);
  const [attestationResult, setAttestationResult] = useState<{
    verdict: string; reasoning: string; certUrl: string | null;
  } | null>(null);

  async function handleLockSource() {
    setLockingSource(true);
    try {
      const res = await fetch(
        `/api/contracts/${contractId}/milestones/${milestoneId}/attestation/lock-source`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            dataSourceType: sourceType,
            dataSourceUrl: sourceUrl || undefined,
            apiKey: sourceApiKey || undefined,
          }),
        }
      );
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Lock failed");
      }
      toast.success("Data source locked — it cannot be changed after this point.");
      window.location.reload();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLockingSource(false);
    }
  }

  async function handleTestSource() {
    setTestingSource(true);
    setTestPreview(null);
    try {
      const res = await fetch("/api/attestation/test-source", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          dataSourceType: sourceType,
          dataSourceUrl: sourceUrl,
          apiKey: sourceApiKey || undefined,
        }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Test failed");
      }
      const data = (await res.json()) as { preview: string; totalLength: number };
      setTestPreview(`${data.preview.slice(0, 600)}${data.totalLength > 600 ? "…" : ""}`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setTestingSource(false);
    }
  }

  async function handleRunAttestation() {
    setRunningAttestation(true);
    try {
      const res = await fetch(
        `/api/contracts/${contractId}/milestones/${milestoneId}/attestation/run`,
        { method: "POST" }
      );
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Run failed");
      }
      const data = (await res.json()) as { verdict: string; reasoning: string; certUrl: string | null };
      setAttestationResult(data);
      toast.success(`Attestation complete — verdict: ${data.verdict}`);
      setTimeout(() => window.location.reload(), 2000);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setRunningAttestation(false);
    }
  }

  // ATTESTATION MODE — render separate UI
  if (contractMode === "ATTESTATION" && milestoneId) {
    const isLocked = !!dataSourceLockedAt;
    const verdictColor: Record<string, string> = { YES: "#4ade80", NO: "#f87171", INCONCLUSIVE: "#fbbf24" };

    return (
      <div className="flex flex-col gap-4">
        {/* Attestation status banner */}
        <div
          className="rounded-xl p-4"
          style={{ background: "rgba(196,112,75,0.06)", border: "1px solid rgba(196,112,75,0.2)" }}
        >
          <p className="text-xs font-bold tracking-widest uppercase mb-1" style={{ color: "#C4704B" }}>
            Enterprise Attestation Mode
          </p>
          <p className="text-sm" style={{ color: "#D4B896" }}>
            {isLocked
              ? `Data source locked · ${dataSourceType?.replace("_", " ")}${dataSourceApiKeyHint ? ` (key: …${dataSourceApiKeyHint})` : ""}`
              : "Configure and lock the data source before running attestation."}
          </p>
          {scheduleType && scheduleType !== "ONE_OFF" && (
            <p className="text-xs mt-1" style={{ color: "#8B7355" }}>
              Schedule: {scheduleType}{scheduleNextRun ? ` · Next run: ${new Date(scheduleNextRun).toLocaleDateString()}` : ""}
            </p>
          )}
        </div>

        {/* Last result */}
        {attestationFetchedAt && (
          <div
            className="rounded-xl p-4"
            style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)" }}
          >
            <p className="text-xs uppercase tracking-wider mb-2" style={{ color: "#8B7355" }}>Last Attestation Run</p>
            <p className="text-xs font-mono mb-1" style={{ color: "#A89B8C" }}>
              {new Date(attestationFetchedAt).toLocaleString()} · hash: {attestationFetchedHash?.slice(0, 12)}…
            </p>
            {attestationCertUrl && (
              <a
                href={attestationCertUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs font-medium"
                style={{ color: "#C4704B" }}
              >
                View certificate →
              </a>
            )}
          </div>
        )}

        {/* New attestation result */}
        {attestationResult && (
          <div
            className="rounded-xl p-4"
            style={{
              background: "rgba(255,255,255,0.03)",
              border: `1px solid ${verdictColor[attestationResult.verdict] ?? "#fbbf24"}40`,
            }}
          >
            <p className="text-sm font-bold mb-1" style={{ color: verdictColor[attestationResult.verdict] ?? "#fbbf24" }}>
              {attestationResult.verdict}
            </p>
            <p className="text-sm italic" style={{ color: "#D4B896" }}>{attestationResult.reasoning}</p>
            {attestationResult.certUrl && (
              <a href={attestationResult.certUrl} target="_blank" rel="noopener noreferrer" className="text-xs mt-2 block" style={{ color: "#C4704B" }}>
                View certificate →
              </a>
            )}
          </div>
        )}

        {/* Data source config — only if not locked */}
        {!isLocked && (
          <div className="flex flex-col gap-3">
            <div>
              <label className="text-xs uppercase tracking-wider block mb-1" style={{ color: "#8B7355" }}>Data Source Type</label>
              <select
                value={sourceType}
                onChange={(e) => setSourceType(e.target.value)}
                className="w-full rounded-lg px-3 py-2 text-sm"
                style={{ background: "#1A1512", border: "1px solid rgba(196,112,75,0.3)", color: "#EDE6DD" }}
              >
                <option value="URL_SCRAPE">URL Scrape — public webpage</option>
                <option value="REST_API">REST API — live business data</option>
                <option value="FILE_UPLOAD">File Upload — PDF / report</option>
                <option value="MANUAL_REVIEW">Manual Review — human confirmation</option>
              </select>
            </div>

            {(sourceType === "URL_SCRAPE" || sourceType === "REST_API") && (
              <div>
                <label className="text-xs uppercase tracking-wider block mb-1" style={{ color: "#8B7355" }}>
                  {sourceType === "REST_API" ? "API Endpoint URL" : "URL to Scrape"}
                </label>
                <input
                  type="url"
                  value={sourceUrl}
                  onChange={(e) => setSourceUrl(e.target.value)}
                  placeholder="https://…"
                  className="w-full rounded-lg px-3 py-2 text-sm"
                  style={{ background: "#1A1512", border: "1px solid rgba(196,112,75,0.3)", color: "#EDE6DD" }}
                />
              </div>
            )}

            {sourceType === "REST_API" && (
              <div>
                <label className="text-xs uppercase tracking-wider block mb-1" style={{ color: "#8B7355" }}>API Key (Bearer)</label>
                <input
                  type="password"
                  value={sourceApiKey}
                  onChange={(e) => setSourceApiKey(e.target.value)}
                  placeholder="sk-… or your API key"
                  className="w-full rounded-lg px-3 py-2 text-sm"
                  style={{ background: "#1A1512", border: "1px solid rgba(196,112,75,0.3)", color: "#EDE6DD" }}
                />
                <p className="text-xs mt-1" style={{ color: "#5A4A3A" }}>Stored AES-256 encrypted. Only the last 4 chars are shown after locking.</p>
              </div>
            )}

            {/* Test + Lock buttons */}
            <div className="flex gap-2">
              {(sourceType === "URL_SCRAPE" || sourceType === "REST_API") && (
                <button
                  onClick={handleTestSource}
                  disabled={testingSource || !sourceUrl}
                  className="flex-1 rounded-lg py-2 text-sm font-medium disabled:opacity-40"
                  style={{ background: "rgba(196,112,75,0.1)", color: "#C4704B", border: "1px solid rgba(196,112,75,0.3)" }}
                >
                  {testingSource ? "Fetching preview…" : "Test Source"}
                </button>
              )}
              <button
                onClick={handleLockSource}
                disabled={lockingSource || (sourceType !== "FILE_UPLOAD" && sourceType !== "MANUAL_REVIEW" && !sourceUrl)}
                className="flex-1 rounded-lg py-2 text-sm font-semibold disabled:opacity-40"
                style={{ background: "#C4704B", color: "#fff" }}
              >
                {lockingSource ? "Locking…" : "Lock Data Source"}
              </button>
            </div>

            {/* Preview */}
            {testPreview && (
              <div
                className="rounded-lg p-3 text-xs font-mono overflow-auto max-h-40"
                style={{ background: "#0E0B0A", border: "1px solid rgba(255,255,255,0.08)", color: "#8B7355", whiteSpace: "pre-wrap" }}
              >
                {testPreview}
              </div>
            )}
          </div>
        )}

        {/* Run attestation — only if locked */}
        {isLocked && (
          <button
            onClick={handleRunAttestation}
            disabled={runningAttestation}
            className="w-full rounded-xl py-3 text-sm font-semibold disabled:opacity-40"
            style={{ background: "rgba(74,222,128,0.1)", color: "#4ade80", border: "1px solid rgba(74,222,128,0.3)" }}
          >
            {runningAttestation ? "Running attestation…" : "Run Attestation Now"}
          </button>
        )}
      </div>
    );
  }

  // ── Mint test RLUSD via MockRLUSD.faucet() ───────────────────────────────
  async function handleFaucet() {
    setFaucetLoading(true);
    try {
      const account = await connectMetaMask();
      toast.info("Minting test RLUSD to your wallet…");
      await callFaucet(account, amountRLUSD);
      toast.success(`Minted ${amountRLUSD} RLUSD to your wallet! You can now fund the escrow.`);
    } catch (err) {
      console.error("Faucet error:", err);
      toast.error(extractError(err));
    } finally {
      setFaucetLoading(false);
    }
  }

  // ── Fund escrow via MetaMask ──────────────────────────────────────────────
  async function handleFundEscrow() {
    setFundingStep("approving");
    try {
      const account = await connectMetaMask();

      // 1. Get pre-encoded calldata from backend
      const res = await fetch("/api/escrow/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, milestoneId }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Failed to prepare escrow transaction");
      }
      const { rlusdAddress, escrowContractAddress, approveCalldata, fundCalldata, amountUSD: amountNeeded } =
        await res.json();

      // Pre-flight: check RLUSD balance
      const iface = new (await import("ethers")).ethers.Interface([
        "function balanceOf(address) view returns (uint256)",
        "function decimals() view returns (uint8)",
      ]);
      const balData = iface.encodeFunctionData("balanceOf", [account]);
      const balHex = await window.ethereum!.request({
        method: "eth_call",
        params: [{ to: rlusdAddress, data: balData }, "latest"],
      }) as string;
      const balance = BigInt(balHex);
      const needed = BigInt(Math.round(parseFloat(amountNeeded) * 1_000_000));
      if (balance < needed) {
        const humanBal = (Number(balance) / 1_000_000).toFixed(2);
        throw new Error(
          `Insufficient RLUSD balance. You have ${humanBal} RLUSD but need ${amountNeeded}. Use the faucet link below first.`
        );
      }

      // 2. Step 1 — Approve RLUSD spending
      toast.info("Step 1/2: Approve RLUSD in MetaMask…");
      const approveTxHash = await sendTx(account, rlusdAddress, approveCalldata);
      await waitForReceipt(approveTxHash);

      // 3. Step 2 — Fund escrow
      setFundingStep("funding");
      toast.info("Approved! Step 2/2: Check MetaMask to fund the escrow…");
      const fundTxHash = await sendTx(account, escrowContractAddress, fundCalldata);
      await waitForReceipt(fundTxHash);

      // 4. Confirm with backend — retry a few times in case the RPC hasn't indexed the tx yet
      setFundingStep("confirming");
      toast.info("Confirming on server…");
      let confirmRes: Response | null = null;
      for (let attempt = 0; attempt < 3; attempt++) {
        if (attempt > 0) await new Promise((r) => setTimeout(r, 4000));
        confirmRes = await fetch("/api/escrow/confirm", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ contractId, milestoneId, txHash: fundTxHash }),
        });
        if (confirmRes.ok) break;
        const e = await confirmRes.json();
        // Only retry on "not found / not mined yet" errors
        if (!e.error?.includes("not found")) throw new Error(e.error ?? "Escrow confirm failed");
      }
      if (!confirmRes?.ok) {
        const e = await confirmRes!.json();
        throw new Error(e.error ?? "Escrow confirm failed");
      }

      setFundingStep("done");
      toast.success("Escrow funded! Reloading…");
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      console.error("Escrow funding error:", err);
      setFundingStep("idle");
      toast.error(extractError(err));
    }
  }

  // ── AI verification (SSE stream with retry progress) ─────────────────────
  async function handleVerify(proofId: string) {
    setLoadingVerify(true);
    try {
      const res = await fetch("/api/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ proofId }),
      });

      // Non-200 responses are plain JSON errors (auth, rate limit, validation)
      if (!res.ok) {
        const err = await res.json() as { error?: string };
        throw new Error(err.error ?? "Verification failed");
      }

      // 200 = SSE stream
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          let event: Record<string, unknown>;
          try { event = JSON.parse(line.slice(6)) as Record<string, unknown>; } catch { continue; }

          if (event.type === "retrying") {
            toast.info(
              `AI providers didn't respond (attempt ${(event.n as number) - 1}/3). Retrying in ${event.waitSeconds}s…`,
              { duration: (event.waitSeconds as number) * 1000 }
            );
          } else if (event.type === "attempt" && (event.n as number) > 1) {
            toast.info(`Attempt ${event.n}/3…`);
          } else if (event.type === "error") {
            throw new Error((event.message as string | undefined) ?? "Verification failed");
          } else if (event.type === "complete") {
            if (event.action === "COMPLETED") {
              toast.success("AI approved! Funds auto-released — milestone completed.");
            } else if (event.decision === "YES") {
              toast.success("AI approved! Milestone verified — you can now release the funds.");
            } else {
              toast.error(`AI rejected: ${event.reasoning}`);
            }
            setVerifyDone(true);
            setTimeout(() => window.location.reload(), 1500);
            return;
          }
        }
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Verification failed.");
    } finally {
      setLoadingVerify(false);
    }
  }

  // ── Release funds (platform signs on-chain — no MetaMask needed) ──────────
  async function handleFinishEscrow() {
    setLoadingFinish(true);
    try {
      const res = await fetch("/api/escrow/finish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, milestoneId }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Release failed");
      }
      toast.success("Funds released! Contract completed.");
      setTimeout(() => window.location.reload(), 1500);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Release failed.");
    } finally {
      setLoadingFinish(false);
    }
  }

  // ── Cancel escrow (platform signs on-chain — no MetaMask needed) ──────────
  async function handleCancelEscrow() {
    setLoadingCancel(true);
    try {
      const res = await fetch("/api/escrow/cancel", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, milestoneId }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Cancel failed");
      }
      const data = await res.json();
      if (data.action === "already_closed") {
        toast.success("Escrow already settled. Contract marked as expired.");
      } else {
        toast.success("Escrow cancelled. Funds returned to Grant Giver.");
      }
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Cancel failed.");
    } finally {
      setLoadingCancel(false);
    }
  }

  // ── Manual review (investor approves/rejects) ─────────────────────────────
  async function handleReview(decision: "APPROVE" | "REJECT") {
    setLoadingReview(decision);
    try {
      const res = await fetch("/api/contracts/review", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, decision }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Review failed");
      }
      toast.success(
        decision === "APPROVE"
          ? "Approved! Receiver can now withdraw funds."
          : "Rejected. Receiver can resubmit."
      );
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Review failed.");
    } finally {
      setLoadingReview(null);
    }
  }

  // ── Resubmit proof ────────────────────────────────────────────────────────
  async function handleResubmit() {
    setLoadingResubmit(true);
    try {
      const res = await fetch("/api/contracts/resubmit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contractId, ...(milestoneId ? { milestoneId } : {}) }),
      });
      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.error ?? "Resubmit failed");
      }
      const data = await res.json() as { ok: boolean; status?: string; escalated?: boolean };
      if (data.escalated) {
        toast.info("Too many AI rejections — your case has been escalated to manual review by the Grant Giver.");
      } else {
        toast.success("Contract reset — you can now upload a new proof.");
      }
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Resubmit failed.");
    } finally {
      setLoadingResubmit(false);
    }
  }

  // ── Submit appeal against AI rejection ───────────────────────────────────
  async function handleAppeal() {
    if (!latestProofId) return;
    setLoadingAppeal(true);
    try {
      const res = await fetch(`/api/proof/${latestProofId}/appeal`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rebuttal: appealText }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Appeal failed");
      }
      const data = (await res.json()) as { decision: string; reasoning: string };
      if (data.decision === "OVERTURNED") {
        toast.success("Appeal accepted — escalated to Grant Giver for review.");
      } else {
        toast.error("Appeal dismissed. You can still resubmit a new proof.");
      }
      setTimeout(() => window.location.reload(), 1500);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Appeal failed.");
    } finally {
      setLoadingAppeal(false);
    }
  }

  // ── Submit interim progress update (startup) ─────────────────────────────
  async function handleRenegotiate() {
    if (!milestoneId) return;
    setLoadingRenegotiate(true);
    try {
      const res = await fetch(`/api/contracts/${contractId}/milestones/${milestoneId}/renegotiate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ interimUpdateText: renegotiationText, extensionDays: renegotiationExtDays }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Request failed");
      }
      toast.success("Extension request submitted — the Grant Giver will review it shortly.");
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Request failed.");
    } finally {
      setLoadingRenegotiate(false);
    }
  }

  // ── Investor approves or rejects the extension request ───────────────────
  async function handleRenegotiateRespond(decision: "APPROVE" | "REJECT") {
    if (!milestoneId) return;
    setLoadingRenegotiateRespond(decision);
    try {
      const res = await fetch(`/api/contracts/${contractId}/milestones/${milestoneId}/renegotiate/respond`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ decision }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Request failed");
      }
      toast.success(
        decision === "APPROVE"
          ? "Extension approved! The milestone deadline has been extended."
          : "Extension rejected. The escrow has been cancelled."
      );
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Request failed.");
    } finally {
      setLoadingRenegotiateRespond(null);
    }
  }

  // ── Log a voluntary progress update (startup) ────────────────────────────
  async function handleProgressUpdate() {
    if (!milestoneId) return;
    setLoadingProgressUpdate(true);
    try {
      const res = await fetch(`/api/contracts/${contractId}/milestones/${milestoneId}/progress`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: progressUpdateText }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Request failed");
      }
      toast.success("Progress update shared with the Grant Giver.");
      setProgressUpdateText("");
      setTimeout(() => window.location.reload(), 1200);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Request failed.");
    } finally {
      setLoadingProgressUpdate(false);
    }
  }

  // ── Run AI proof pre-check (Feature I) ───────────────────────────────────
  async function handlePreCheck() {
    if (!milestoneId) return;
    setLoadingPreCheck(true);
    setPreCheckResult(null);
    try {
      const res = await fetch("/api/proof/precheck", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ milestoneId }),
      });
      if (!res.ok) {
        const err = (await res.json()) as { error?: string };
        throw new Error(err.error ?? "Pre-check failed");
      }
      const data = await res.json() as { verdict: "LIKELY_PASS" | "LIKELY_FAIL" | "BORDERLINE"; feedback: string; suggestions: string[] };
      setPreCheckResult(data);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Pre-check failed.");
    } finally {
      setLoadingPreCheck(false);
    }
  }

  const isExpired = new Date() >= new Date(cancelAfter);

  // ── AWAITING_ESCROW: investor funds via MetaMask (or demo simulation) ──────
  if (status === "AWAITING_ESCROW") {
    if (!isDemo && viewerWallet !== investorAddress) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(196,112,75,0.08)", border: "1px solid rgba(196,112,75,0.25)" }}>
          <p className="text-sm font-medium" style={{ color: "#E8935A" }}>
            Waiting for the Grant Giver to fund the escrow.
          </p>
        </div>
      );
    }

    if (isDemo) {
      const fundLabel =
        totalMilestones > 1 && milestoneNumber !== null
          ? `Fund Milestone ${milestoneNumber}/${totalMilestones} (Demo)`
          : "Fund Escrow (Demo)";

      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(196,112,75,0.08)", border: "1px solid rgba(196,112,75,0.25)" }}>
          {/* Demo overlay */}
          {demoStep === "overlay" && demoOverlayText && (
            <div
              className="flex flex-col gap-2 p-4 rounded-lg"
              style={{ background: "rgba(196,112,75,0.12)", border: "1px solid rgba(196,112,75,0.4)" }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: "#C4704B" }}>
                Demo: What MetaMask would do
              </p>
              <p className="text-sm leading-relaxed" style={{ color: "#D4B896" }}>{demoOverlayText}</p>
              <p className="text-xs" style={{ color: "#8B7355" }}>Simulating confirmation…</p>
            </div>
          )}
          <div className="flex items-center gap-2">
            <span
              className="px-2 py-0.5 rounded-full text-xs font-semibold uppercase tracking-widest"
              style={{ background: "rgba(196,112,75,0.15)", color: "#C4704B", border: "1px solid rgba(196,112,75,0.3)" }}
            >
              Demo Mode
            </span>
            <p className="text-sm font-medium" style={{ color: "#E8935A" }}>
              {totalMilestones > 1 && milestoneNumber !== null
                ? `Milestone ${milestoneNumber} of ${totalMilestones}${milestoneTitle ? `: ${milestoneTitle}` : ""}`
                : "Fund the escrow to lock RLUSD."}
            </p>
          </div>
          <p className="text-xs" style={{ color: "#A89B8C" }}>
            Amount: <strong style={{ color: "#D4B896" }}>{amountRLUSD} RLUSD</strong> — in the real app MetaMask
            opens twice: once to approve RLUSD spending, then to sign the escrow transaction on XRPL EVM Sidechain.
          </p>
          <button
            onClick={() =>
              advanceDemo(
                "fund",
                `MetaMask popup 1/2: Approve ${amountRLUSD} RLUSD spending for the escrow contract.\n\nMetaMask popup 2/2: Sign the createMilestone() transaction on XRPL EVM Sidechain (Chain ID 1449000). Gas: ~0.001 XRP.\n\nBoth transactions confirmed — funds locked in escrow.`
              )
            }
            disabled={demoStep !== "idle"}
            className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
            style={{ background: "#C4704B", color: "#171311" }}
          >
            {demoStep === "loading" ? "Confirming…" : demoStep === "overlay" ? "MetaMask open…" : fundLabel}
          </button>
        </div>
      );
    }

    const fundingLabel =
      totalMilestones > 1 && milestoneNumber !== null
        ? `Fund Milestone ${milestoneNumber}/${totalMilestones} via MetaMask`
        : "Fund Escrow via MetaMask";

    const stepLabel: Record<typeof fundingStep, string> = {
      idle: fundingLabel,
      approving: "Step 1/2: Approving RLUSD…",
      funding: "Step 2/2: Funding escrow…",
      confirming: "Confirming…",
      done: "Done!",
    };

    return (
      <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(196,112,75,0.08)", border: "1px solid rgba(196,112,75,0.25)" }}>
        <p className="text-sm font-medium" style={{ color: "#E8935A" }}>
          {totalMilestones > 1 && milestoneNumber !== null
            ? `Milestone ${milestoneNumber} of ${totalMilestones}${milestoneTitle ? `: ${milestoneTitle}` : ""} — fund the escrow to lock funds.`
            : "Both parties have committed. Fund the escrow to lock funds."}
        </p>
        <p className="text-xs" style={{ color: "#A89B8C" }}>
          Amount: <strong style={{ color: "#D4B896" }}>{amountRLUSD} RLUSD</strong> — MetaMask will ask you to
          approve the token transfer, then sign the escrow transaction.
        </p>
        {isMobileNoWallet && (
          <div
            className="flex items-start gap-2 p-3 rounded-lg text-xs leading-relaxed"
            style={{ background: "rgba(234,179,8,0.08)", border: "1px solid rgba(234,179,8,0.3)", color: "#ca8a04" }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" style={{ flexShrink: 0, marginTop: 1 }}>
              <path d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
            <span>
              <strong>Desktop required for funding.</strong> MetaMask is a browser extension that only works on desktop (Chrome, Firefox, Brave). Please open this contract on your computer to fund the escrow.
            </span>
          </div>
        )}
        <button
          onClick={handleFundEscrow}
          disabled={fundingStep !== "idle" || faucetLoading || isMobileNoWallet}
          className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
          style={{ background: "#C4704B", color: "#171311" }}
        >
          {stepLabel[fundingStep]}
        </button>
        <button
          onClick={handleFaucet}
          disabled={faucetLoading || fundingStep !== "idle"}
          className="text-xs underline disabled:opacity-50 disabled:no-underline"
          style={{ color: "#A89B8C" }}
        >
          {faucetLoading ? "Minting…" : `No RLUSD? Get ${amountRLUSD} test RLUSD from faucet`}
        </button>
      </div>
    );
  }

  // ── FUNDED: startup uploads proof ─────────────────────────────────────────
  if (status === "FUNDED") {
    if (!isDemo && viewerWallet !== startupAddress) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(96,165,250,0.07)", border: "1px solid rgba(96,165,250,0.2)" }}>
          <p className="text-sm font-medium" style={{ color: "#7DB8F7" }}>
            Waiting for the Receiver to upload milestone proof.
          </p>
          {/* Progress updates list (investor view) */}
          {progressUpdates.length > 0 && (
            <div className="flex flex-col gap-2 mt-1">
              <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#A89B8C" }}>
                Progress Updates ({progressUpdates.length})
              </p>
              {progressUpdates.map((u) => (
                <div
                  key={u.id}
                  className="flex flex-col gap-0.5 p-3 rounded-lg"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(96,165,250,0.15)" }}
                >
                  <p className="text-xs leading-relaxed" style={{ color: "#EDE6DD" }}>{u.text}</p>
                  <p className="text-xs" style={{ color: "#6B5E52" }}>
                    {new Date(u.createdAt).toLocaleString()}
                  </p>
                </div>
              ))}
            </div>
          )}
        </div>
      );
    }

    if (isDemo) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(96,165,250,0.07)", border: "1px solid rgba(96,165,250,0.2)" }}>
          {demoStep === "overlay" && demoOverlayText && (
            <div
              className="flex flex-col gap-2 p-4 rounded-lg"
              style={{ background: "rgba(96,165,250,0.1)", border: "1px solid rgba(96,165,250,0.35)" }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: "#7DB8F7" }}>
                Demo: What happens on the Receiver side
              </p>
              <p className="text-sm leading-relaxed" style={{ color: "#A8C8F7" }}>{demoOverlayText}</p>
              <p className="text-xs" style={{ color: "#6B8AAA" }}>Uploading demo proof…</p>
            </div>
          )}
          <div className="flex items-center gap-2">
            <span
              className="px-2 py-0.5 rounded-full text-xs font-semibold uppercase tracking-widest"
              style={{ background: "rgba(96,165,250,0.12)", color: "#7DB8F7", border: "1px solid rgba(96,165,250,0.3)" }}
            >
              Demo Mode
            </span>
            <p className="text-sm font-medium" style={{ color: "#7DB8F7" }}>
              Escrow funded — Receiver uploads milestone proof.
            </p>
          </div>
          <p className="text-xs" style={{ color: "#A89B8C" }}>
            In the real app the Receiver uploads a PDF or links a GitHub repo. For this demo we use a
            pre-built proof from <strong style={{ color: "#D4B896" }}>Acme AI Labs</strong> with MVP metrics,
            signed LOIs, and GitHub activity.
          </p>
          <button
            onClick={() =>
              advanceDemo(
                "submit_proof",
                "The Receiver (Acme AI Labs) uploads their milestone proof PDF.\n\nFile: acme-ai-labs-milestone-proof.pdf — 11 pages with screenshots, signed LOIs, and GitHub activity report.\n\nProof submitted and logged on XRPL audit trail."
              )
            }
            disabled={demoStep !== "idle"}
            className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
            style={{ background: "#7DB8F7", color: "#171311" }}
          >
            {demoStep === "loading" ? "Uploading…" : demoStep === "overlay" ? "Uploading proof…" : "Submit Demo Proof"}
          </button>
        </div>
      );
    }

    return (
      <div className="flex flex-col gap-3">
        {milestoneId && (
          <ProofGuidance
            contractId={contractId}
            milestoneId={milestoneId}
            initialGuidance={milestoneGuidance}
          />
        )}
        {/* Progress update form (startup view) */}
        {milestoneId && (
          <div
            className="flex flex-col gap-2 p-4 rounded-xl"
            style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(196,112,75,0.15)" }}
          >
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#A89B8C" }}>
                Share a Progress Update
              </p>
              {progressUpdates.length > 0 && (
                <span className="text-xs" style={{ color: "#6B5E52" }}>
                  {progressUpdates.length} update{progressUpdates.length !== 1 ? "s" : ""} shared
                </span>
              )}
            </div>
            <p className="text-xs" style={{ color: "rgba(168,155,140,0.7)" }}>
              Optional — keep the Grant Giver informed of your progress before submitting proof.
            </p>
            {progressUpdates.length > 0 && (
              <div className="flex flex-col gap-1.5 mb-1">
                {progressUpdates.slice(0, 2).map((u) => (
                  <div
                    key={u.id}
                    className="flex flex-col gap-0.5 p-2.5 rounded-lg"
                    style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(196,112,75,0.12)" }}
                  >
                    <p className="text-xs leading-relaxed" style={{ color: "#A89B8C" }}>{u.text}</p>
                    <p className="text-xs" style={{ color: "#6B5E52" }}>
                      {new Date(u.createdAt).toLocaleString()}
                    </p>
                  </div>
                ))}
              </div>
            )}
            <textarea
              value={progressUpdateText}
              onChange={(e) => setProgressUpdateText(e.target.value)}
              placeholder="e.g. Backend API is done, working on frontend integration now — 70% complete overall…"
              rows={3}
              maxLength={1000}
              className="w-full rounded-lg p-3 text-sm resize-none outline-none"
              style={{
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(196,112,75,0.2)",
                color: "#EDE6DD",
                fontFamily: "inherit",
              }}
            />
            <div className="flex items-center justify-between gap-3">
              <span className="text-xs" style={{ color: "rgba(168,155,140,0.4)" }}>
                {progressUpdateText.length}/1000
              </span>
              <button
                onClick={handleProgressUpdate}
                disabled={loadingProgressUpdate || progressUpdateText.trim().length < 20}
                className="rounded-lg px-3 py-1.5 text-xs font-semibold transition-all disabled:opacity-40"
                style={{ background: "rgba(196,112,75,0.15)", border: "1px solid rgba(196,112,75,0.35)", color: "#C4704B" }}
              >
                {loadingProgressUpdate ? "Sharing…" : "Share Update"}
              </button>
            </div>
          </div>
        )}
        <ProofUpload
          contractId={contractId}
          milestoneId={milestoneId}
          onUploaded={() => window.location.reload()}
        />
      </div>
    );
  }

  // ── PROOF_SUBMITTED: trigger AI verification ──────────────────────────────
  if (status === "PROOF_SUBMITTED" && latestProofId && !verifyDone) {
    const isStartup = isDemo || viewerWallet === startupAddress;

    if (isDemo) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(96,165,250,0.07)", border: "1px solid rgba(96,165,250,0.2)" }}>
          {demoStep === "overlay" && demoOverlayText && (
            <div
              className="flex flex-col gap-2 p-4 rounded-lg"
              style={{ background: "rgba(96,165,250,0.1)", border: "1px solid rgba(96,165,250,0.35)" }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: "#7DB8F7" }}>
                Demo: AI Verification running
              </p>
              <p className="text-sm leading-relaxed" style={{ color: "#A8C8F7" }}>{demoOverlayText}</p>
            </div>
          )}
          <div className="flex items-center gap-2">
            <span
              className="px-2 py-0.5 rounded-full text-xs font-semibold uppercase tracking-widest"
              style={{ background: "rgba(96,165,250,0.12)", color: "#7DB8F7", border: "1px solid rgba(96,165,250,0.3)" }}
            >
              Demo Mode
            </span>
            <p className="text-sm font-medium" style={{ color: "#7DB8F7" }}>Proof uploaded. Run the 5-model AI vote.</p>
          </div>
          <div
            className="flex items-center gap-3 px-4 py-3 rounded-lg"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(96,165,250,0.2)" }}
          >
            <span className="text-xs font-mono px-1.5 py-0.5 rounded" style={{ background: "rgba(96,165,250,0.15)", color: "#7DB8F7" }}>PDF</span>
            <span className="text-sm flex-1" style={{ color: "#EDE6DD" }}>acme-ai-labs-milestone-proof.pdf</span>
          </div>
          <p className="text-xs" style={{ color: "#A89B8C" }}>
            cascrow runs <strong style={{ color: "#D4B896" }}>5 AI models in parallel</strong> (Claude, Gemini,
            GPT-4o, Mistral, Cerebras). 3 of 5 YES votes needed to release funds.
          </p>
          <button
            onClick={() =>
              advanceDemo(
                "verify",
                "Querying 5 AI models in parallel:\n• Claude Haiku · Gemini Flash · GPT-4o-mini · Mistral Small · Cerebras/Qwen3\n\nAnalysing proof against milestone criteria…"
              )
            }
            disabled={demoStep !== "idle"}
            className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
            style={{ background: "#C4704B", color: "#171311" }}
          >
            {demoStep === "loading"
              ? "Verifying…"
              : demoStep === "overlay"
              ? "Running 5 AI models…"
              : "Run AI Verification"}
          </button>
        </div>
      );
    }

    return (
      <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(96,165,250,0.07)", border: "1px solid rgba(96,165,250,0.2)" }}>
        <p className="text-sm" style={{ color: "#7DB8F7" }}>
          {isStartup ? "Proof uploaded. Ready for AI verification." : "The Receiver has submitted proof. AI verification is pending."}
        </p>
        {latestProofFileUrl && isStartup && (
          <a
            href={latestProofFileUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-4 py-3 rounded-lg transition-colors"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(96,165,250,0.2)" }}
          >
            <span className="text-xs font-mono px-1.5 py-0.5 rounded" style={{ background: "rgba(96,165,250,0.15)", color: "#7DB8F7" }}>
              {latestProofFileName?.split(".").pop()?.toUpperCase() ?? "FILE"}
            </span>
            <span className="text-sm flex-1 truncate" style={{ color: "#EDE6DD" }}>{latestProofFileName}</span>
            <span className="text-xs" style={{ color: "#7DB8F7" }}>Open ↗</span>
          </a>
        )}
        {isStartup && (
          <div className="flex flex-col gap-3">
            {/* Pre-check result panel */}
            {preCheckResult && (() => {
              const isPass = preCheckResult.verdict === "LIKELY_PASS";
              const isFail = preCheckResult.verdict === "LIKELY_FAIL";
              const color = isPass ? "#6EE09A" : isFail ? "#F87171" : "#D4A03C";
              const bg = isPass ? "rgba(74,222,128,0.06)" : isFail ? "rgba(248,113,113,0.06)" : "rgba(212,160,60,0.06)";
              const border = isPass ? "rgba(74,222,128,0.2)" : isFail ? "rgba(248,113,113,0.2)" : "rgba(212,160,60,0.25)";
              const label = isPass ? "Likely to Pass" : isFail ? "Likely to Fail" : "Borderline";
              return (
                <div className="flex flex-col gap-2 p-3 rounded-lg" style={{ background: bg, border: `1px solid ${border}` }}>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-semibold uppercase tracking-wide" style={{ color }}>
                      Pre-Check: {label}
                    </span>
                  </div>
                  <p className="text-xs leading-relaxed" style={{ color: "#A89B8C" }}>{preCheckResult.feedback}</p>
                  {preCheckResult.suggestions.length > 0 && (
                    <ul className="flex flex-col gap-1 mt-0.5">
                      {preCheckResult.suggestions.map((s, i) => (
                        <li key={i} className="flex gap-1.5 text-xs" style={{ color: "#A89B8C" }}>
                          <span style={{ color, flexShrink: 0 }}>→</span>
                          <span>{s}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              );
            })()}
            <div className="flex gap-2">
              <button
                onClick={handlePreCheck}
                disabled={loadingPreCheck || loadingVerify}
                className="rounded-lg py-2.5 px-4 text-sm font-semibold transition-colors disabled:opacity-50"
                style={{
                  background: "rgba(196,112,75,0.1)",
                  color: "#C4704B",
                  border: "1px solid rgba(196,112,75,0.35)",
                  whiteSpace: "nowrap",
                }}
              >
                {loadingPreCheck ? "Checking…" : preCheckResult ? "Re-check" : "Test my proof"}
              </button>
              <button
                onClick={() => handleVerify(latestProofId)}
                disabled={loadingVerify || loadingPreCheck}
                className="flex-1 rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
                style={{ background: "#C4704B", color: "#171311" }}
              >
                {loadingVerify ? "Verifying…" : "Run AI Verification"}
              </button>
              <ProofUpload
                contractId={contractId}
                milestoneId={milestoneId}
                onUploaded={() => window.location.reload()}
                replaceMode
              />
            </div>
          </div>
        )}
      </div>
    );
  }

  // ── PENDING_REVIEW: investor manually approves or rejects ─────────────────
  if (status === "PENDING_REVIEW") {
    return (
      <div className="flex flex-col gap-4 p-5 rounded-xl" style={{ background: "rgba(196,112,75,0.08)", border: "1px solid rgba(196,112,75,0.25)" }}>
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold" style={{ color: "#E8935A" }}>Manual Review Required</p>
          {latestProofConfidence !== null && (
            <span
              className="text-xs font-medium px-2 py-0.5 rounded-full"
              style={{ background: "rgba(196,112,75,0.15)", color: "#E8935A" }}
            >
              AI Confidence: {latestProofConfidence}%
            </span>
          )}
        </div>

        {latestProofReasoning && (
          <div className="flex flex-col gap-1">
            <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#A89B8C" }}>
              AI Analysis
            </p>
            <p className="text-sm leading-relaxed rounded-lg p-3" style={{ background: "rgba(255,255,255,0.04)", color: "#EDE6DD" }}>
              {latestProofReasoning}
            </p>
          </div>
        )}

        {latestProofFileUrl && (
          <a
            href={latestProofFileUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-4 py-3 rounded-lg transition-colors"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(196,112,75,0.2)" }}
          >
            <span className="text-xs font-mono px-1.5 py-0.5 rounded" style={{ background: "rgba(196,112,75,0.15)", color: "#C4704B" }}>
              {latestProofFileName?.split(".").pop()?.toUpperCase() ?? "FILE"}
            </span>
            <span className="text-sm flex-1 truncate" style={{ color: "#EDE6DD" }}>{latestProofFileName}</span>
            <span className="text-xs" style={{ color: "#C4704B" }}>Open ↗</span>
          </a>
        )}

        {viewerWallet === investorAddress ? (
          <div className="flex flex-col gap-2">
            <p className="text-xs" style={{ color: "#A89B8C" }}>
              The AI was not confident enough for an automatic decision. Review the proof above and decide manually.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => handleReview("APPROVE")}
                disabled={loadingReview !== null}
                style={{
                  background: "#16a34a",
                  color: "#fff",
                  flex: 1,
                  padding: "8px 16px",
                  borderRadius: "8px",
                  border: "none",
                  fontWeight: 600,
                  cursor: loadingReview !== null ? "not-allowed" : "pointer",
                  opacity: loadingReview !== null ? 0.6 : 1,
                }}
              >
                {loadingReview === "APPROVE" ? "Approving…" : "✓ Approve"}
              </button>
              <button
                onClick={() => {
                  if (!confirmReject) { setConfirmReject(true); return; }
                  setConfirmReject(false);
                  handleReview("REJECT");
                }}
                disabled={loadingReview !== null}
                style={{
                  background: confirmReject ? "rgba(248,113,113,0.25)" : "rgba(248,113,113,0.1)",
                  color: "#F87171",
                  flex: 1,
                  padding: "8px 16px",
                  borderRadius: "8px",
                  border: "1px solid rgba(248,113,113,0.3)",
                  fontWeight: 600,
                  cursor: loadingReview !== null ? "not-allowed" : "pointer",
                  opacity: loadingReview !== null ? 0.6 : 1,
                }}
              >
                {loadingReview === "REJECT" ? "Rejecting…" : confirmReject ? "Confirm: Reject?" : "✗ Reject"}
              </button>
            </div>
          </div>
        ) : (
          <p className="text-sm" style={{ color: "#A89B8C" }}>
            The Grant Giver is reviewing your proof. You will be notified once a decision has been made.
          </p>
        )}
      </div>
    );
  }

  // ── VERIFIED: startup releases funds (platform calls contract server-side) ─
  if (status === "VERIFIED") {
    if (!isDemo && viewerWallet !== startupAddress) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(74,222,128,0.07)", border: "1px solid rgba(74,222,128,0.2)" }}>
          <p className="text-sm font-medium" style={{ color: "#6EE09A" }}>
            Milestone approved. The Receiver can now withdraw the funds.
          </p>
        </div>
      );
    }

    if (isDemo) {
      return (
        <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(74,222,128,0.07)", border: "1px solid rgba(74,222,128,0.2)" }}>
          {demoStep === "overlay" && demoOverlayText && (
            <div
              className="flex flex-col gap-2 p-4 rounded-lg"
              style={{ background: "rgba(74,222,128,0.08)", border: "1px solid rgba(74,222,128,0.3)" }}
            >
              <p className="text-xs font-bold uppercase tracking-widest" style={{ color: "#6EE09A" }}>
                Demo: Releasing funds
              </p>
              <p className="text-sm leading-relaxed" style={{ color: "#A8F0C8" }}>{demoOverlayText}</p>
            </div>
          )}
          <div className="flex items-center gap-2">
            <span
              className="px-2 py-0.5 rounded-full text-xs font-semibold uppercase tracking-widest"
              style={{ background: "rgba(74,222,128,0.1)", color: "#6EE09A", border: "1px solid rgba(74,222,128,0.25)" }}
            >
              Demo Mode
            </span>
            <p className="text-sm font-medium" style={{ color: "#6EE09A" }}>
              AI approved! Release the funds to the Receiver.
            </p>
          </div>
          <p className="text-xs" style={{ color: "#A89B8C" }}>
            The platform wallet calls <code style={{ color: "#D4B896" }}>releaseMilestone()</code> on the XRPL EVM
            smart contract — no MetaMask required. RLUSD is transferred to the Receiver. An NFT certificate is
            minted on XRPL Mainnet.
          </p>
          <button
            onClick={() =>
              advanceDemo(
                "release",
                "Platform calls releaseMilestone() on XRPL EVM Sidechain — 15,000 RLUSD sent to Receiver wallet.\n\nNFT certificate minted on XRPL Mainnet via NFTokenMint transaction.\n\nMilestone marked COMPLETED. Reputation score updated."
              )
            }
            disabled={demoStep !== "idle"}
            className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
            style={{ background: "#4ade80", color: "#171311" }}
          >
            {demoStep === "loading"
              ? "Releasing…"
              : demoStep === "overlay"
              ? "Minting NFT certificate…"
              : "Release Funds + Mint NFT Certificate"}
          </button>
        </div>
      );
    }

    return (
      <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(74,222,128,0.07)", border: "1px solid rgba(74,222,128,0.2)" }}>
        <p className="text-sm font-medium" style={{ color: "#6EE09A" }}>
          Milestone approved! Click below to receive your RLUSD — no wallet signing required.
        </p>
        <button
          onClick={handleFinishEscrow}
          disabled={loadingFinish}
          className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
          style={{ background: "#C4704B", color: "#171311" }}
        >
          {loadingFinish ? "Releasing funds…" : "Release Funds"}
        </button>
      </div>
    );
  }

  // ── REJECTED: Appeal Wizard + resubmit ───────────────────────────────────
  if (status === "REJECTED") {
    const appealFiled = latestProofAppealStatus !== null;
    const appealUpheld = latestProofAppealStatus === "REJECTED"; // "REJECTED" = upheld/dismissed

    return (
      <div className="flex flex-col gap-4 p-5 rounded-xl" style={{ background: "rgba(248,113,113,0.07)", border: "1px solid rgba(248,113,113,0.2)" }}>
        <p className="text-sm font-medium" style={{ color: "#F87171" }}>AI rejected the proof.</p>

        {/* Objections panel */}
        {latestProofAiObjections && latestProofAiObjections.length > 0 && (
          <div className="flex flex-col gap-2">
            <p className="text-xs uppercase tracking-wide font-medium" style={{ color: "#A89B8C" }}>
              Why it was rejected
            </p>
            <div className="flex flex-col gap-1.5">
              {latestProofAiObjections.map((obj, i) => (
                <div
                  key={i}
                  className="flex gap-2.5 items-start p-2.5 rounded-lg"
                  style={{ background: "rgba(248,113,113,0.06)", border: "1px solid rgba(248,113,113,0.15)" }}
                >
                  <code
                    className="text-xs font-mono flex-shrink-0"
                    style={{ color: "#F87171", opacity: 0.65, marginTop: 1 }}
                  >
                    {obj.code}
                  </code>
                  <p className="text-xs leading-relaxed" style={{ color: "#EDE6DD" }}>
                    {obj.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Appeal dismissed result */}
        {appealUpheld && latestProofAppealReasoning && (
          <div
            className="flex flex-col gap-1.5 p-3 rounded-lg"
            style={{ background: "rgba(248,113,113,0.08)", border: "1px solid rgba(248,113,113,0.2)" }}
          >
            <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#F87171" }}>
              Appeal dismissed
            </p>
            <p className="text-xs leading-relaxed" style={{ color: "#A89B8C" }}>
              {latestProofAppealReasoning}
            </p>
          </div>
        )}

        {/* Expired: investor cancels */}
        {isExpired ? (
          <>
            <p className="text-xs" style={{ color: "#F87171", opacity: 0.8 }}>
              Deadline has passed. Cancel the escrow to recover your RLUSD.
            </p>
            {viewerWallet === investorAddress && (
              <button
                onClick={() => {
                  if (!confirmCancel) { setConfirmCancel(true); return; }
                  setConfirmCancel(false);
                  handleCancelEscrow();
                }}
                disabled={loadingCancel}
                className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
                style={{
                  background: confirmCancel ? "rgba(248,113,113,0.3)" : "rgba(248,113,113,0.15)",
                  color: "#F87171",
                  border: "1px solid rgba(248,113,113,0.3)",
                }}
              >
                {loadingCancel ? "Cancelling…" : confirmCancel ? "Confirm: Cancel & Recover?" : "Cancel Escrow & Recover Funds"}
              </button>
            )}
          </>
        ) : viewerWallet === startupAddress ? (
          <>
            {/* Appeal form — only if no appeal filed yet */}
            {!appealFiled && (
              <div className="flex flex-col gap-2.5">
                <div>
                  <p className="text-xs font-medium" style={{ color: "#D4B896" }}>
                    Challenge the decision
                  </p>
                  <p className="text-xs mt-0.5" style={{ color: "rgba(168,155,140,0.7)" }}>
                    Explain specifically why the AI was wrong. Reference the objections above.
                  </p>
                </div>
                <textarea
                  value={appealText}
                  onChange={(e) => setAppealText(e.target.value)}
                  placeholder="e.g. The screenshot on page 2 clearly shows the app live on the App Store with a visible timestamp of 2025-03-01, which is within the milestone window…"
                  rows={4}
                  maxLength={1500}
                  className="w-full rounded-lg p-3 text-sm resize-none outline-none"
                  style={{
                    background: "rgba(255,255,255,0.04)",
                    border: "1px solid rgba(248,113,113,0.25)",
                    color: "#EDE6DD",
                    fontFamily: "inherit",
                  }}
                />
                <div className="flex items-center justify-between gap-3">
                  <span className="text-xs" style={{ color: "rgba(168,155,140,0.4)" }}>
                    {appealText.length}/1500
                  </span>
                  <div className="flex items-center gap-3">
                    <button
                      onClick={handleResubmit}
                      disabled={loadingResubmit || loadingAppeal}
                      className="text-xs disabled:opacity-40 transition-opacity"
                      style={{ color: "#A89B8C" }}
                    >
                      {loadingResubmit ? "Resetting…" : "Skip — resubmit instead"}
                    </button>
                    <button
                      onClick={handleAppeal}
                      disabled={loadingAppeal || appealText.trim().length < 20}
                      className="rounded-lg px-4 py-1.5 text-xs font-semibold transition-all disabled:opacity-40"
                      style={{ background: "#C4704B", color: "#171311" }}
                    >
                      {loadingAppeal ? "Submitting…" : "Submit Appeal"}
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* After upheld appeal: resubmit button */}
            {appealUpheld && (
              <button
                onClick={handleResubmit}
                disabled={loadingResubmit}
                className="w-full rounded-lg py-2 text-sm font-medium transition-colors disabled:opacity-50"
                style={{
                  background: "rgba(196,112,75,0.1)",
                  border: "1px solid rgba(196,112,75,0.35)",
                  color: "#C4704B",
                }}
              >
                {loadingResubmit ? "Resetting…" : "Resubmit New Proof"}
              </button>
            )}
          </>
        ) : (
          <p className="text-xs" style={{ color: "#F87171", opacity: 0.8 }}>
            The proof was rejected. The Receiver will need to resubmit a new proof.
          </p>
        )}
      </div>
    );
  }

  // ── RENEGOTIATING: startup submits interim update / investor approves ────
  if (status === "RENEGOTIATING") {
    const windowClosed = renegotiationDeadline ? new Date() > new Date(renegotiationDeadline) : false;
    const extensionRequested = renegotiationStatus === "EXTENSION_REQUESTED";
    const isStartup = viewerWallet === startupAddress;
    const isInvestor = viewerWallet === investorAddress;

    // Countdown display
    const windowLabel = (() => {
      if (!renegotiationDeadline || windowClosed) return "Window closed";
      const msLeft = new Date(renegotiationDeadline).getTime() - Date.now();
      const hLeft = Math.max(0, Math.floor(msLeft / (1000 * 60 * 60)));
      const mLeft = Math.max(0, Math.floor((msLeft % (1000 * 60 * 60)) / (1000 * 60)));
      return hLeft > 0 ? `${hLeft}h ${mLeft}m remaining` : `${mLeft}m remaining`;
    })();

    return (
      <div
        className="flex flex-col gap-4 p-5 rounded-xl"
        style={{ background: "rgba(212,160,60,0.07)", border: "1px solid rgba(212,160,60,0.3)" }}
      >
        <div className="flex items-center justify-between flex-wrap gap-2">
          <p className="text-sm font-semibold" style={{ color: "#D4A03C" }}>
            Renegotiation Window Open
          </p>
          <span
            className="text-xs font-medium px-2 py-0.5 rounded-full"
            style={{ background: "rgba(212,160,60,0.12)", color: "#D4A03C", border: "1px solid rgba(212,160,60,0.25)" }}
          >
            {windowLabel}
          </span>
        </div>

        <p className="text-xs" style={{ color: "#A89B8C" }}>
          The milestone deadline has passed. The Receiver has a limited window to submit a progress update and request an extension.
        </p>

        {/* ── Startup: submit progress update ────────────────────────────── */}
        {isStartup && !extensionRequested && !windowClosed && (
          <div className="flex flex-col gap-3">
            <div>
              <p className="text-xs font-medium" style={{ color: "#D4B896" }}>
                Your progress update
              </p>
              <p className="text-xs mt-0.5" style={{ color: "rgba(168,155,140,0.7)" }}>
                Describe what you have done so far and what remains. Min 100 characters.
              </p>
            </div>
            <textarea
              value={renegotiationText}
              onChange={(e) => setRenegotiationText(e.target.value)}
              placeholder="e.g. We have completed the backend API and 70% of the frontend. The remaining work is the payment integration, which is scoped and ready to build…"
              rows={4}
              maxLength={3000}
              className="w-full rounded-lg p-3 text-sm resize-none outline-none"
              style={{
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(212,160,60,0.25)",
                color: "#EDE6DD",
                fontFamily: "inherit",
              }}
            />
            <div className="flex items-center gap-2">
              <p className="text-xs" style={{ color: "#A89B8C" }}>Extension requested:</p>
              {([7, 14, 30] as const).map((d) => (
                <button
                  key={d}
                  onClick={() => setRenegotiationExtDays(d)}
                  className="px-3 py-1 rounded-lg text-xs font-semibold transition-colors"
                  style={{
                    background: renegotiationExtDays === d ? "#D4A03C" : "rgba(212,160,60,0.1)",
                    color: renegotiationExtDays === d ? "#171311" : "#D4A03C",
                    border: `1px solid ${renegotiationExtDays === d ? "#D4A03C" : "rgba(212,160,60,0.3)"}`,
                  }}
                >
                  {d} days
                </button>
              ))}
            </div>
            <div className="flex items-center justify-between gap-3">
              <span className="text-xs" style={{ color: "rgba(168,155,140,0.4)" }}>
                {renegotiationText.length}/3000
              </span>
              <button
                onClick={handleRenegotiate}
                disabled={loadingRenegotiate || renegotiationText.trim().length < 100}
                className="rounded-lg px-4 py-1.5 text-xs font-semibold transition-all disabled:opacity-40"
                style={{ background: "#D4A03C", color: "#171311" }}
              >
                {loadingRenegotiate ? "Submitting…" : "Submit Extension Request"}
              </button>
            </div>
          </div>
        )}

        {/* ── Startup: request submitted, waiting ────────────────────────── */}
        {isStartup && extensionRequested && (
          <div
            className="flex flex-col gap-2 p-3 rounded-lg"
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(212,160,60,0.2)" }}
          >
            <p className="text-xs font-medium" style={{ color: "#D4A03C" }}>
              Extension request submitted
            </p>
            <p className="text-xs" style={{ color: "#A89B8C" }}>
              The Grant Giver is reviewing your request. You will be notified once a decision has been made.
            </p>
            {interimAiAssessment && (
              <p className="text-xs leading-relaxed mt-1" style={{ color: "#A89B8C" }}>
                <strong style={{ color: "#D4B896" }}>AI assessment: </strong>
                {interimAiAssessment}
              </p>
            )}
          </div>
        )}

        {/* ── Startup: window closed without submitting ───────────────────── */}
        {isStartup && !extensionRequested && windowClosed && (
          <p className="text-xs" style={{ color: "#F87171" }}>
            The renegotiation window has closed. The escrow will be cancelled shortly.
          </p>
        )}

        {/* ── Investor: waiting for startup to submit ─────────────────────── */}
        {isInvestor && !extensionRequested && (
          <div className="flex flex-col gap-2">
            <p className="text-xs" style={{ color: "#A89B8C" }}>
              Waiting for the Receiver to submit a progress update.
              {windowClosed
                ? " The window has closed — the escrow will be automatically cancelled."
                : ""}
            </p>
            <button
              onClick={() => {
                if (!confirmCancelReneg) { setConfirmCancelReneg(true); return; }
                setConfirmCancelReneg(false);
                handleCancelEscrow();
              }}
              disabled={loadingCancel}
              className="w-full rounded-lg py-2 text-xs font-semibold transition-colors disabled:opacity-50"
              style={{
                background: confirmCancelReneg ? "rgba(248,113,113,0.2)" : "rgba(248,113,113,0.07)",
                color: "#F87171",
                border: "1px solid rgba(248,113,113,0.25)",
              }}
            >
              {loadingCancel ? "Cancelling…" : confirmCancelReneg ? "Confirm: Cancel escrow & recover funds?" : "Skip renegotiation — cancel escrow"}
            </button>
          </div>
        )}

        {/* ── Investor: review extension request ─────────────────────────── */}
        {isInvestor && extensionRequested && (
          <div className="flex flex-col gap-3">
            {interimUpdateText && (
              <div className="flex flex-col gap-1">
                <p className="text-xs font-medium uppercase tracking-wide" style={{ color: "#A89B8C" }}>
                  Progress Update
                </p>
                <p
                  className="text-sm leading-relaxed rounded-lg p-3"
                  style={{ background: "rgba(255,255,255,0.04)", color: "#EDE6DD" }}
                >
                  {interimUpdateText}
                </p>
              </div>
            )}

            {interimAiAssessment && (
              <div
                className="flex flex-col gap-1.5 p-3 rounded-lg"
                style={{
                  background: interimAiPositive
                    ? "rgba(74,222,128,0.06)"
                    : "rgba(248,113,113,0.06)",
                  border: `1px solid ${interimAiPositive ? "rgba(74,222,128,0.2)" : "rgba(248,113,113,0.2)"}`,
                }}
              >
                <p
                  className="text-xs font-medium uppercase tracking-wide"
                  style={{ color: interimAiPositive ? "#6EE09A" : "#F87171" }}
                >
                  AI Assessment — {interimAiPositive ? "Plausible" : "Unlikely"}
                </p>
                <p className="text-xs leading-relaxed" style={{ color: "#A89B8C" }}>
                  {interimAiAssessment}
                </p>
              </div>
            )}

            {extensionDays && (
              <p className="text-xs" style={{ color: "#A89B8C" }}>
                Requested extension:{" "}
                <strong style={{ color: "#D4B896" }}>{extensionDays} days</strong>
              </p>
            )}

            <div className="flex gap-3">
              <button
                onClick={() => handleRenegotiateRespond("APPROVE")}
                disabled={loadingRenegotiateRespond !== null}
                style={{
                  background: "#16a34a",
                  color: "#fff",
                  flex: 1,
                  padding: "8px 16px",
                  borderRadius: "8px",
                  border: "none",
                  fontWeight: 600,
                  cursor: loadingRenegotiateRespond !== null ? "not-allowed" : "pointer",
                  opacity: loadingRenegotiateRespond !== null ? 0.6 : 1,
                }}
              >
                {loadingRenegotiateRespond === "APPROVE" ? "Approving…" : "✓ Approve Extension"}
              </button>
              <button
                onClick={() => handleRenegotiateRespond("REJECT")}
                disabled={loadingRenegotiateRespond !== null}
                style={{
                  background: "rgba(248,113,113,0.1)",
                  color: "#F87171",
                  flex: 1,
                  padding: "8px 16px",
                  borderRadius: "8px",
                  border: "1px solid rgba(248,113,113,0.3)",
                  fontWeight: 600,
                  cursor: loadingRenegotiateRespond !== null ? "not-allowed" : "pointer",
                  opacity: loadingRenegotiateRespond !== null ? 0.6 : 1,
                }}
              >
                {loadingRenegotiateRespond === "REJECT" ? "Rejecting…" : "✗ Reject & Cancel"}
              </button>
            </div>
          </div>
        )}
      </div>
    );
  }

  // ── Deadline passed on FUNDED/PROOF_SUBMITTED ─────────────────────────────
  if (["FUNDED", "PROOF_SUBMITTED"].includes(status) && isExpired) {
    return (
      <div className="flex flex-col gap-3 p-5 rounded-xl" style={{ background: "rgba(196,112,75,0.08)", border: "1px solid rgba(196,112,75,0.25)" }}>
        <p className="text-sm font-medium" style={{ color: "#E8935A" }}>
          Deadline has passed. Cancel the escrow to recover your RLUSD.
        </p>
        {viewerWallet === investorAddress && (
          <button
            onClick={handleCancelEscrow}
            disabled={loadingCancel}
            className="w-full rounded-lg py-2.5 text-sm font-semibold transition-colors disabled:opacity-50"
            style={{ background: "rgba(248,113,113,0.15)", color: "#F87171", border: "1px solid rgba(248,113,113,0.3)" }}
          >
            {loadingCancel ? "Cancelling…" : "Cancel Escrow & Recover Funds"}
          </button>
        )}
      </div>
    );
  }

  return null;
}
