/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MilestoneFundEscrow {
  export type MilestoneEscrowStruct = {
    investor: AddressLike;
    startup: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    funded: boolean;
    completed: boolean;
    cancelled: boolean;
  };

  export type MilestoneEscrowStructOutput = [
    investor: string,
    startup: string,
    amount: bigint,
    deadline: bigint,
    funded: boolean,
    completed: boolean,
    cancelled: boolean
  ] & {
    investor: string;
    startup: string;
    amount: bigint;
    deadline: bigint;
    funded: boolean;
    completed: boolean;
    cancelled: boolean;
  };
}

export interface MilestoneFundEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelMilestone"
      | "escrows"
      | "fundMilestone"
      | "getMilestoneEscrow"
      | "owner"
      | "platform"
      | "releaseMilestone"
      | "renounceOwnership"
      | "rlusd"
      | "setPlatform"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestoneCancelled"
      | "MilestoneFunded"
      | "MilestoneReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundMilestone",
    values: [BytesLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestoneEscrow",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rlusd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPlatform",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestoneEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rlusd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MilestoneCancelledEvent {
  export type InputTuple = [
    contractId: BytesLike,
    milestoneOrder: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    milestoneOrder: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    contractId: string;
    milestoneOrder: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneFundedEvent {
  export type InputTuple = [
    contractId: BytesLike,
    milestoneOrder: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    milestoneOrder: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    contractId: string;
    milestoneOrder: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneReleasedEvent {
  export type InputTuple = [
    contractId: BytesLike,
    milestoneOrder: BigNumberish,
    startup: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    contractId: string,
    milestoneOrder: bigint,
    startup: string,
    amount: bigint
  ];
  export interface OutputObject {
    contractId: string;
    milestoneOrder: bigint;
    startup: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MilestoneFundEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MilestoneFundEscrow;
  waitForDeployment(): Promise<this>;

  interface: MilestoneFundEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelMilestone: TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean, boolean] & {
        investor: string;
        startup: string;
        amount: bigint;
        deadline: bigint;
        funded: boolean;
        completed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  fundMilestone: TypedContractMethod<
    [
      contractId: BytesLike,
      milestoneOrder: BigNumberish,
      startup: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getMilestoneEscrow: TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [MilestoneFundEscrow.MilestoneEscrowStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platform: TypedContractMethod<[], [string], "view">;

  releaseMilestone: TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rlusd: TypedContractMethod<[], [string], "view">;

  setPlatform: TypedContractMethod<
    [_platform: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelMilestone"
  ): TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean, boolean] & {
        investor: string;
        startup: string;
        amount: bigint;
        deadline: bigint;
        funded: boolean;
        completed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundMilestone"
  ): TypedContractMethod<
    [
      contractId: BytesLike,
      milestoneOrder: BigNumberish,
      startup: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMilestoneEscrow"
  ): TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [MilestoneFundEscrow.MilestoneEscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseMilestone"
  ): TypedContractMethod<
    [contractId: BytesLike, milestoneOrder: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rlusd"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPlatform"
  ): TypedContractMethod<[_platform: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MilestoneCancelled"
  ): TypedContractEvent<
    MilestoneCancelledEvent.InputTuple,
    MilestoneCancelledEvent.OutputTuple,
    MilestoneCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneFunded"
  ): TypedContractEvent<
    MilestoneFundedEvent.InputTuple,
    MilestoneFundedEvent.OutputTuple,
    MilestoneFundedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneReleased"
  ): TypedContractEvent<
    MilestoneReleasedEvent.InputTuple,
    MilestoneReleasedEvent.OutputTuple,
    MilestoneReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MilestoneCancelled(bytes32,uint256,address,uint256)": TypedContractEvent<
      MilestoneCancelledEvent.InputTuple,
      MilestoneCancelledEvent.OutputTuple,
      MilestoneCancelledEvent.OutputObject
    >;
    MilestoneCancelled: TypedContractEvent<
      MilestoneCancelledEvent.InputTuple,
      MilestoneCancelledEvent.OutputTuple,
      MilestoneCancelledEvent.OutputObject
    >;

    "MilestoneFunded(bytes32,uint256,address,uint256)": TypedContractEvent<
      MilestoneFundedEvent.InputTuple,
      MilestoneFundedEvent.OutputTuple,
      MilestoneFundedEvent.OutputObject
    >;
    MilestoneFunded: TypedContractEvent<
      MilestoneFundedEvent.InputTuple,
      MilestoneFundedEvent.OutputTuple,
      MilestoneFundedEvent.OutputObject
    >;

    "MilestoneReleased(bytes32,uint256,address,uint256)": TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;
    MilestoneReleased: TypedContractEvent<
      MilestoneReleasedEvent.InputTuple,
      MilestoneReleasedEvent.OutputTuple,
      MilestoneReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
